apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-httpd
  namespace: httpd

spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Mi
  storageClassName: manual
